// Dữ liệu mẫu được tạo tự động
export const sampleData = {
  products: [
    {
      id: 1,
      title: "Attack On Titan Artisan Keycap - Eren Yeager Edition",
      shortDesc:
        "Bring the warrior spirit to your keyboard! Inspired by Eren Yeager from Attack On Titan, this artisan keycap is hand-crafted with premium resin and detailed design.",
      longDesc:
        "Inspired by Eren Yeager from Attack On Titan, this artisan keycap captures his determination and rage. Each keycap is handmade with premium resin, creating a unique aesthetic for every piece. Perfect for mechanical keyboard enthusiasts and anime collectors alike.",
      image: "/img/keycap/AttackOnTitan/Eren.jpg",
      mainImage: "/img/keycap/AttackOnTitan/Eren.jpg",
      thumbnails: ["/img/keycap/AttackOnTitan/Eren_blank.jpg"],
      specs: {
        category: "Attack On Titan",
        brand: "KeySmith",
        color: "Brown – Black – Silver",
      },
      price: 75,
      importPrice: 45,
      stock: 9,
      sold: 0,
      status: "ready",
    },
    {
      id: 2,
      title: "Attack On Titan Artisan Keycap - Fight for Paradis Edition",
      shortDesc:
        "Ignite the flames of resistance! Inspired by the epic battle to protect Paradis in Attack On Titan, this artisan keycap embodies courage and unyielding hope.",
      longDesc:
        "Inspired by the fiery battlegrounds of humanity’s last stand, the Attack On Titan Artisan Keycap - Fight for Paradis Edition symbolizes the bravery and determination of the Survey Corps. Handcrafted with premium resin, every detail—from the blazing flames to the iconic Wings of Freedom emblem—is meticulously sculpted, bringing a powerful and artistic touch to your mechanical keyboard.",
      image: "/img/keycap/AttackOnTitan/Fight_for_Paradis.webp",
      mainImage: "/img/keycap/AttackOnTitan/Fight_for_Paradis.webp",
      thumbnails: [],
      specs: {
        category: "Attack On Titan",
        brand: "KeySmith",
        color: "Red – Black – Silver",
      },
      price: 68,
      importPrice: 41,
      stock: 7,
      sold: 0,
      status: "ready",
    },
    {
      id: 3,
      title: "Attack On Titan Artisan Keycap - Reiner Keycap",
      shortDesc:
        "Unleash the storm within! Forged in the chaos of battle, this keycap channels the power of heroes who never surrender. Press it, and feel destiny move beneath your fingertips.",
      longDesc:
        "Inspired by the fiery battlegrounds of humanity’s last stand, the Attack On Titan Artisan Keycap - Reiner Keycap symbolizes the bravery and determination of the Survey Corps. Handcrafted with premium resin, every detail—from the blazing flames to the iconic Wings of Freedom emblem—is meticulously sculpted, bringing a powerful and artistic touch to your mechanical keyboard.",
      image: "/img/keycap/AttackOnTitan/Reiner.jpg",
      mainImage: "/img/keycap/AttackOnTitan/Reiner.jpg",
      thumbnails: ["/img/keycap/AttackOnTitan/Reiner_blank.jpg"],
      specs: {
        category: "Attack On Titan",
        brand: "KeySmith",
        color: "Red – Black – Silver",
      },
      price: 72,
      importPrice: 43,
      stock: 10,
      sold: 0,
      status: "ready",
    },
    {
      id: 4,
      title: "Attack On Titan Artisan Keycap - Scout Keycap",
      shortDesc:
        "Born from the heart of a dying star, this keycap burns with eternal fire. Each press ignites your spirit, reminding you that legends are not born—they’re forged.",
      longDesc:
        "Set sail toward the Grand Line with the One Piece Artisan Keycap – King of the Pirates Edition. Featuring a detailed miniature of the iconic Straw Hat symbol, this handcrafted resin piece captures the spirit of freedom, adventure, and the unbreakable will to chase your dreams.",
      image: "/img/keycap/AttackOnTitan/Scout.jpg",
      mainImage: "/img/keycap/AttackOnTitan/Scout.jpg",
      thumbnails: ["/img/keycap/AttackOnTitan/Scout_blank.jpg"],
      specs: {
        category: "Attack On Titan",
        brand: "KeySmith",
        color: "Ocean Blue – Gold – Ivory",
      },
      price: 65,
      importPrice: 39,
      stock: 6,
      sold: 0,
      status: "ready",
    },
    {
      id: 5,
      title: "Attack On Titan Artisan Keycap - Spacebar Keycap",
      shortDesc:
        "No sound. No mercy. With every strike, thunder answers your call. Let the storm of your will reshape the battlefield.",
      longDesc:
        "Dive into a world of neon lights and shattered reality with the Cyberpunk Neon Core Artisan Keycap. Designed for futurists and rebels alike, this glowing masterpiece fuses bold color contrasts with intricate resin sculpting for a truly electrifying typing experience.",
      image: "/img/keycap/AttackOnTitan/spacebar.jpg",
      mainImage: "/img/keycap/AttackOnTitan/Spacebar.jpg",
      thumbnails: ["/img/keycap/AttackOnTitan/Spacebar_blank.jpg"],
      specs: {
        category: "Attack On Titan",
        brand: "KeySmith",
        color: "Neon Pink – Electric Blue – Jet Black",
      },
      price: 85,
      importPrice: 51,
      stock: 8,
      sold: 0,
      status: "outofstock",
    },
    {
      id: 6,
      title: "LOTR Artisan Keycap - Durin's Axe Keycap",
      shortDesc:
        "From the depths of forgotten realms, this keycap rises — a relic of power and purpose. With each press, echoes of ancient warriors awaken, urging your fingers toward victory eternal.",
      longDesc:
        "Forged in the heart of a dying star, the Stellar Forge Artisan Keycap captures the essence of cosmic creation. Each swirl of resin mirrors the birth of galaxies — luminous, infinite, and full of mystery. A statement piece for dreamers who type among the stars.",
      image: "/img/keycap/LOTR/durin/durin's_axe.jpg",
      mainImage: "/img/keycap/LOTR/durin/durin's_axe.jpg",
      thumbnails: [],
      specs: {
        category: "Lord Of the Ring",
        brand: "KeySmith",
        color: "Midnight Blue – Silver – Nebula Purple",
      },
      price: 78,
      importPrice: 47,
      stock: 7,
      sold: 0,
      status: "ready",
    },
    {
      id: 7,
      title: "LOTR Artisan Keycap - Durin's Folk Keycap",
      shortDesc:
        "Tempered in lightning and silence, this keycap crackles with untamed will. Touch it, and feel the pulse of storms long caged — waiting only for your command to break free.",
      longDesc:
        "Born from the ashes of forgotten legends, the Phoenix Rebirth Artisan Keycap embodies renewal and undying spirit. Each fiery gradient is hand-blended, symbolizing the endless cycle of destruction and creation — a perfect harmony between flame and focus.",
      image: "/img/keycap/LOTR/durin/durin's_folk.jpg",
      mainImage: "/img/keycap/LOTR/durin/durin's_folk.jpg",
      thumbnails: [],
      specs: {
        category: "Lord Of the Ring",
        brand: "KeySmith",
        color: "Crimson – Amber – Obsidian",
      },
      price: 82,
      importPrice: 49,
      stock: 9,
      sold: 0,
      status: "ready",
    },
    {
      id: 8,
      title: "LOTR Artisan Keycap - Durin's Helm Keycap",
      shortDesc:
        "Beneath your fingertips lies the roar of a thousand battles. This keycap hums with defiance, daring you to press onward — for destiny bows only to those who never yield.",
      longDesc:
        "Draw strength from the depths of darkness with the Shadow Reaver Artisan Keycap. Inspired by the mysterious warriors of the night, this piece fuses sleek obsidian tones with metallic accents — a tribute to precision, stealth, and silent power.",
      image: "/img/keycap/LOTR/durin/durin's_helm.jpg",
      mainImage: "/img/keycap/LOTR/durin/durin's_helm.jpg",
      thumbnails: [],
      specs: {
        category: "Lord Of the Ring",
        brand: "KeySmith",
        color: "Jet Black – Steel Gray – Scarlet",
      },
      price: 76,
      importPrice: 46,
      stock: 10,
      sold: 0,
      status: "ready",
    },
    {
      id: 9,
      title: "LOTR Artisan Keycap - Horn of Gondor Keycap",
      shortDesc:
        "Forged from shattered crowns and burning skies, this keycap bears the mark of conquerors. Each strike rekindles the flame of glory — a reminder that empires rise from a single press.",
      longDesc:
        "Echoing the tranquility of ancient mountains, the Zen Wave Artisan Keycap captures the calm between chaos. Hand-poured with flowing resin patterns, it brings balance and serenity to every keystroke — a quiet reminder of focus and flow.",
      image: "/img/keycap/LOTR/gondor/horn_of_gordor.jpg",
      mainImage: "/img/keycap/LOTR/gondor/horn_of_gordor.jpg",
      thumbnails: [
        "/img/keycap/LOTR/gondor/horn_of_gordor_1.jpg",
        "/img/keycap/LOTR/gondor/horn_of_gordor_white.jpg",
      ],
      specs: {
        category: "Lord Of the Ring",
        brand: "KeySmith",
        color: "Ivory – Ocean Blue – Stone Gray",
      },
      price: 88,
      importPrice: 53,
      stock: 6,
      sold: 0,
      status: "outofstock",
    },
    {
      id: 10,
      title: "LOTR Artisan Keycap - Palantir Keycap",
      shortDesc:
        "Bound by runes of triumph, this keycap sings of battles yet to come. Each press summons the echo of victory — a promise carved in the language of heroes.",
      longDesc:
        "Awaken the frost within with the Glacial Spirit Artisan Keycap. Crafted to resemble ancient ice sealed in time, its crystalline surface refracts light like frozen magic — cool, sharp, and endlessly captivating on any keyboard setup.",
      image: "/img/keycap/LOTR/gondor/palantir.jpg",
      mainImage: "/img/keycap/LOTR/gondor/palantir.jpg",
      thumbnails: [
        "/img/keycap/LOTR/gondor/palantir_1.jpg",
        "/img/keycap/LOTR/gondor/palantir_white.jpg",
      ],
      specs: {
        category: "Lord Of the Ring",
        brand: "KeySmith",
        color: "Arctic Blue – White – Silver",
      },
      price: 95,
      importPrice: 57,
      stock: 9,
      sold: 0,
      status: "ready",
    },
    {
      id: 11,
      title: "LOTR Artisan Keycap - White Tree Keycap",
      shortDesc:
        "Born from the heart of an ancient volcano, this keycap channels pure elemental power. Each press unleashes a surge of molten energy — crafted for those who thrive in the heat of creation.",
      longDesc:
        "The Magmaheart Artisan Keycap is a masterpiece forged in flame. Layered resin mimics the glow of flowing lava, blending vivid orange veins with deep obsidian undertones. A statement of strength, transformation, and unstoppable momentum — for creators who burn bright.",
      image: "/img/keycap/LOTR/gondor/white_tree.jpg",
      mainImage: "/img/keycap/LOTR/gondor/white_tree.jpg",
      thumbnails: [
        "/img/keycap/LOTR/gondor/white_tree_1.jpg",
        "/img/keycap/LOTR/gondor/white_tree_white.jpg",
      ],
      specs: {
        category: "Lord Of the Ring",
        brand: "KeySmith",
        color: "Molten Orange – Obsidian – Gold",
      },
      price: 85,
      importPrice: 51,
      stock: 8,
      sold: 0,
      status: "ready",
    },
    {
      id: 12,
      title: "One Piece Artisan Keycap - One Piece Keycap 1",
      shortDesc:
        "Glimmering like the first frost of winter, this keycap evokes quiet elegance and crisp clarity. Each press is a gentle whisper of serenity.",
      longDesc:
        "The Frosted Peak Artisan Keycap reflects the delicate shimmer of morning frost on untouched snow. Crafted with icy blue and silver gradients, it brings a cool, calming presence to every keystroke.",
      image: "/img/keycap/OnePiece/1.png",
      mainImage: "/img/keycap/OnePiece/1.png",
      thumbnails: [],
      specs: {
        category: "One Piece",
        brand: "KeySmith",
        color: "Ice Blue – Silver – Pale Gray",
      },
      price: 62,
      importPrice: 37,
      stock: 10,
      sold: 0,
      status: "outofstock",
    },
    {
      id: 13,
      title: "One Piece Artisan Keycap - One Piece Keycap 2",
      shortDesc:
        "Bathed in the glow of twilight, this keycap carries the mystery of dusk and the calm before nightfall. Every touch feels like capturing the last light of day.",
      longDesc:
        "The Twilight Ember Artisan Keycap mirrors the sky at sunset, blending soft purples and warm amber tones. Its luminous resin evokes reflection and tranquility as day transitions into night.",
      image: "/img/keycap/OnePiece/2.png",
      mainImage: "/img/keycap/OnePiece/2.png",
      thumbnails: [],
      specs: {
        category: "One Piece",
        brand: "KeySmith",
        color: "Purple – Amber – Rose Gold",
      },
      price: 64,
      importPrice: 38,
      stock: 6,
      sold: 0,
      status: "ready",
    },
    {
      id: 14,
      title: "YuGiOh Artisan Keycap - Yu-Gi-Oh! Keycap 1",
      shortDesc:
        "Radiating the gentle warmth of spring morning, this keycap brings freshness and optimism with every press. It’s a small celebration of new beginnings.",
      longDesc:
        "The Spring Blossom Artisan Keycap evokes the tender hues of early flowers under soft sunlight. Crafted from pastel pinks and golden highlights, it’s a reminder of growth and renewal with each keystroke.",
      image: "/img/keycap/Yugioh/1.jpg",
      mainImage: "/img/keycap/Yugioh/1.jpg",
      thumbnails: ["/img/keycap/Yugioh/YuGiOh-BEWDragon-5.webp"],
      specs: {
        category: "Yugioh",
        brand: "KeySmith",
        color: "Pale Pink – Soft Gold – Cream",
      },
      price: 70,
      importPrice: 42,
      stock: 8,
      sold: 0,
      status: "ready",
    },
    {
      id: 15,
      title: "YuGiOh Artisan Keycap - Yu-Gi-Oh! Keycap 2",
      shortDesc:
        "Shimmering like starlight on a quiet night, this keycap carries calm and wonder with every press. A tiny piece of the cosmos at your fingertips.",
      longDesc:
        "The Starlit Sky Artisan Keycap captures the magic of a clear night, blending deep navy with sparkling silver flecks. Each stroke evokes serenity and the infinite beauty of the cosmos.",
      image: "/img/keycap/Yugioh/2.jpg",
      mainImage: "/img/keycap/Yugioh/2.jpg",
      thumbnails: [],
      specs: {
        category: "Yugioh",
        brand: "KeySmith",
        color: "Midnight Blue – Silver – Soft Black",
      },
      price: 73,
      importPrice: 44,
      stock: 7,
      sold: 0,
      status: "ready",
    },
    {
      id: 16,
      title: "YuGiOh Artisan Keycap - YGOv3 Ra 11 Keycap",
      shortDesc:
        "Like morning dew on a quiet meadow, this keycap brings freshness and subtle brilliance. Each press feels like a gentle touch of nature’s calm.",
      longDesc:
        "The Dewy Meadow Artisan Keycap embodies the delicate beauty of early morning light on fresh greenery. Soft greens and pearlescent whites combine to inspire calm and renewal at every keystroke.",
      image: "/img/keycap/Yugioh/YGOv3-Ra-11.webp",
      mainImage: "/img/keycap/Yugioh/YGOv3-Ra-11.webp",
      thumbnails: [],
      specs: {
        category: "Yugioh",
        brand: "KeySmith",
        color: "Soft Green – White – Pale Yellow",
      },
      price: 80,
      importPrice: 48,
      stock: 9,
      sold: 0,
      status: "ready",
    },
    {
      id: 17,
      title: "YuGiOh Artisan Keycap - YuGiOh DarkMagicianGirl 5 Keycap",
      shortDesc:
        "Bathed in the soft glow of moonlight, this keycap exudes calm and quiet elegance. Each press feels like a gentle embrace of night’s serenity.",
      longDesc:
        "The Moonlit Silhouette Artisan Keycap captures the subtle radiance of moonlight against a tranquil sky. With gradients of silver and pale blue, it evokes reflection, calm, and quiet wonder with every keystroke.",
      image: "/img/keycap/Yugioh/YuGiOh-DarkMagicianGirl-5.webp",
      mainImage: "/img/keycap/Yugioh/YuGiOh-DarkMagicianGirl-5.webp",
      thumbnails: [],
      specs: {
        category: "Yugioh",
        brand: "KeySmith",
        color: "Silver – Pale Blue – Soft Gray",
      },
      price: 86,
      importPrice: 52,
      stock: 10,
      sold: 0,
      status: "outofstock",
    },
    {
      id: 18,
      title: "YuGiOh Artisan Keycap - YuGiOh V2 Concept 11-4 Keycap",
      shortDesc:
        "Awash in the colors of a gentle sunrise, this keycap inspires hope and tranquility. Each press feels like the first breath of a new day.",
      longDesc:
        "The Aurora Morning Artisan Keycap blends soft pinks, warm golds, and creamy whites to recreate the serene beauty of dawn. Its radiant resin encourages calm, optimism, and gentle focus with every keystroke.",
      image: "/img/keycap/Yugioh/YuGiOh-V2-Concept-11-4.webp",
      mainImage: "/img/keycap/Yugioh/YuGiOh-V2-Concept-11-4.webp",
      thumbnails: [],
      specs: {
        category: "Yugioh",
        brand: "KeySmith",
        color: "Pale Pink – Warm Gold – Cream",
      },
      price: 55,
      importPrice: 33,
      stock: 8,
      sold: 0,
      status: "ready",
    },
    {
      id: 19,
      title: "YuGiOh Artisan Keycap - YuGiOh V2 Concept 11-6 Keycap",
      shortDesc:
        "Glinting with the soft glow of morning frost, this keycap exudes a crisp, refreshing calm. Each press feels like a spark of clarity at the start of the day.",
      longDesc:
        "The Frosted Dawn Artisan Keycap captures the serene sparkle of frost-kissed mornings. Crafted with pale blues, soft whites, and subtle silver shimmer, it brings clarity, calm, and freshness to each keystroke.",
      image: "/img/keycap/Yugioh/YuGiOh-V2-Concept-11-6.webp",
      mainImage: "/img/keycap/Yugioh/YuGiOh-V2-Concept-11-6.webp",
      thumbnails: [],
      specs: {
        category: "Yugioh",
        brand: "KeySmith",
        color: "Pale Blue – White – Silver",
      },
      price: 58,
      importPrice: 35,
      stock: 7,
      sold: 0,
      status: "ready",
    },
  ],
  customers: [
    {
      username: "cust01",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "An",
      lastName: "Nguyen",
      email: "an.nguyen@example.com",
      phone: "0901000001",
      address: "Hanoi, Vietnam",
      dateOfBirth: "1990-04-15",
      status: "active",
    },
    {
      username: "cust02",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Binh",
      lastName: "Tran",
      email: "binh.tran@example.com",
      phone: "0901000002",
      address: "Ho Chi Minh City, Vietnam",
      dateOfBirth: "1988-09-02",
      status: "active",
    },
    {
      username: "cust03",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Chi",
      lastName: "Le",
      email: "chi.le@example.com",
      phone: "0901000003",
      address: "Da Nang, Vietnam",
      dateOfBirth: "1995-06-30",
      status: "active",
    },
    {
      username: "cust04",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Dung",
      lastName: "Pham",
      email: "dung.pham@example.com",
      phone: "0901000004",
      address: "Hai Phong, Vietnam",
      dateOfBirth: "1985-12-11",
      status: "active",
    },
    {
      username: "cust05",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Em",
      lastName: "Ho",
      email: "em.ho@example.com",
      phone: "0901000005",
      address: "Can Tho, Vietnam",
      dateOfBirth: "1992-03-21",
      status: "active",
    },
    {
      username: "cust06",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Minh",
      lastName: "Vo",
      email: "minh.vo@example.com",
      phone: "0901000006",
      address: "Nha Trang, Vietnam",
      dateOfBirth: "1991-07-08",
      status: "active",
    },
    {
      username: "cust07",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Hoa",
      lastName: "Pham",
      email: "hoa.pham@example.com",
      phone: "0901000007",
      address: "Hue, Vietnam",
      dateOfBirth: "1998-11-19",
      status: "active",
    },
    {
      username: "cust08",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Khanh",
      lastName: "Do",
      email: "khanh.do@example.com",
      phone: "0901000008",
      address: "Vung Tau, Vietnam",
      dateOfBirth: "1987-02-03",
      status: "inactive",
    },
    {
      username: "cust09",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Lan",
      lastName: "Nguyen",
      email: "lan.nguyen@example.com",
      phone: "0901000009",
      address: "Da Lat, Vietnam",
      dateOfBirth: "1993-08-27",
      status: "active",
    },
    {
      username: "cust10",
      password: "pass123",
      img: "/img/blank-image.png",
      firstName: "Quynh",
      lastName: "Pham",
      email: "quynh.pham@example.com",
      phone: "0901000010",
      address: "Bien Hoa, Vietnam",
      dateOfBirth: "1996-01-05",
      status: "active",
    },
  ],
  orders: [
    {
      idOrder: 1,
      username: "cust01",
      items: [{ id: 1, quantity: 1, unitPrice: 75, amountPrice: 75 }],
      totalPrice: 75,
      date: "2025-11-10T00:00:00.000Z",
      userDeliveryPhone: "0901000001",
      userDeliveryAdress: "Hanoi, Vietnam",
      status: "new",
    },
    {
      idOrder: 2,
      username: "cust02",
      items: [{ id: 2, quantity: 2, unitPrice: 68, amountPrice: 136 }],
      totalPrice: 136,
      date: "2025-11-09T00:00:00.000Z",
      userDeliveryPhone: "0901000002",
      userDeliveryAdress: "Ho Chi Minh City, Vietnam",
      status: "processing",
    },
    {
      idOrder: 3,
      username: "cust03",
      items: [
        { id: 3, quantity: 1, unitPrice: 72, amountPrice: 72 },
        { id: 5, quantity: 1, unitPrice: 85, amountPrice: 85 },
      ],
      totalPrice: 157,
      date: "2025-11-08T00:00:00.000Z",
      userDeliveryPhone: "0901000003",
      userDeliveryAdress: "Da Nang, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 4,
      username: "cust04",
      items: [{ id: 4, quantity: 3, unitPrice: 65, amountPrice: 195 }],
      totalPrice: 195,
      date: "2025-11-07T00:00:00.000Z",
      userDeliveryPhone: "0901000004",
      userDeliveryAdress: "Hai Phong, Vietnam",
      status: "cancelled",
    },
    {
      idOrder: 5,
      username: "cust05",
      items: [{ id: 6, quantity: 1, unitPrice: 78, amountPrice: 78 }],
      totalPrice: 78,
      date: "2025-11-06T00:00:00.000Z",
      userDeliveryPhone: "0901000005",
      userDeliveryAdress: "Can Tho, Vietnam",
      status: "new",
    },
    {
      idOrder: 6,
      username: "cust06",
      items: [{ id: 7, quantity: 2, unitPrice: 82, amountPrice: 164 }],
      totalPrice: 164,
      date: "2025-11-05T00:00:00.000Z",
      userDeliveryPhone: "0901000006",
      userDeliveryAdress: "Nha Trang, Vietnam",
      status: "processing",
    },
    {
      idOrder: 7,
      username: "cust07",
      items: [{ id: 8, quantity: 1, unitPrice: 76, amountPrice: 76 }],
      totalPrice: 76,
      date: "2025-11-04T00:00:00.000Z",
      userDeliveryPhone: "0901000007",
      userDeliveryAdress: "Hue, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 8,
      username: "cust08",
      items: [{ id: 9, quantity: 1, unitPrice: 88, amountPrice: 88 }],
      totalPrice: 88,
      date: "2025-11-03T00:00:00.000Z",
      userDeliveryPhone: "0901000008",
      userDeliveryAdress: "Vung Tau, Vietnam",
      status: "cancelled",
    },
    {
      idOrder: 9,
      username: "cust09",
      items: [{ id: 10, quantity: 1, unitPrice: 95, amountPrice: 95 }],
      totalPrice: 95,
      date: "2025-11-02T00:00:00.000Z",
      userDeliveryPhone: "0901000009",
      userDeliveryAdress: "Da Lat, Vietnam",
      status: "new",
    },
    {
      idOrder: 10,
      username: "cust10",
      items: [{ id: 11, quantity: 2, unitPrice: 85, amountPrice: 170 }],
      totalPrice: 170,
      date: "2025-11-01T00:00:00.000Z",
      userDeliveryPhone: "0901000010",
      userDeliveryAdress: "Bien Hoa, Vietnam",
      status: "processing",
    },
    // 10
    {
      idOrder: 11,
      username: "cust01",
      items: [{ id: 12, quantity: 1, unitPrice: 62, amountPrice: 62 }],
      totalPrice: 62,
      date: "2025-10-31T00:00:00.000Z",
      userDeliveryPhone: "0901000001",
      userDeliveryAdress: "Hanoi, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 12,
      username: "cust02",
      items: [
        { id: 13, quantity: 1, unitPrice: 64, amountPrice: 64 },
        { id: 1, quantity: 1, unitPrice: 75, amountPrice: 75 },
      ],
      totalPrice: 139,
      date: "2025-10-30T00:00:00.000Z",
      userDeliveryPhone: "0901000002",
      userDeliveryAdress: "Ho Chi Minh City, Vietnam",
      status: "cancelled",
    },
    {
      idOrder: 13,
      username: "cust03",
      items: [{ id: 14, quantity: 1, unitPrice: 70, amountPrice: 70 }],
      totalPrice: 70,
      date: "2025-10-29T00:00:00.000Z",
      userDeliveryPhone: "0901000003",
      userDeliveryAdress: "Da Nang, Vietnam",
      status: "new",
    },
    {
      idOrder: 14,
      username: "cust04",
      items: [{ id: 15, quantity: 2, unitPrice: 73, amountPrice: 146 }],
      totalPrice: 146,
      date: "2025-10-28T00:00:00.000Z",
      userDeliveryPhone: "0901000004",
      userDeliveryAdress: "Hai Phong, Vietnam",
      status: "processing",
    },
    {
      idOrder: 15,
      username: "cust05",
      items: [{ id: 16, quantity: 1, unitPrice: 80, amountPrice: 80 }],
      totalPrice: 80,
      date: "2025-10-27T00:00:00.000Z",
      userDeliveryPhone: "0901000005",
      userDeliveryAdress: "Can Tho, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 16,
      username: "cust06",
      items: [{ id: 17, quantity: 1, unitPrice: 86, amountPrice: 86 }],
      totalPrice: 86,
      date: "2025-10-26T00:00:00.000Z",
      userDeliveryPhone: "0901000006",
      userDeliveryAdress: "Nha Trang, Vietnam",
      status: "cancelled",
    },
    {
      idOrder: 17,
      username: "cust07",
      items: [{ id: 18, quantity: 3, unitPrice: 55, amountPrice: 165 }],
      totalPrice: 165,
      date: "2025-10-25T00:00:00.000Z",
      userDeliveryPhone: "0901000007",
      userDeliveryAdress: "Hue, Vietnam",
      status: "new",
    },
    {
      idOrder: 18,
      username: "cust08",
      items: [{ id: 19, quantity: 2, unitPrice: 58, amountPrice: 116 }],
      totalPrice: 116,
      date: "2025-10-24T00:00:00.000Z",
      userDeliveryPhone: "0901000008",
      userDeliveryAdress: "Vung Tau, Vietnam",
      status: "processing",
    },
    {
      idOrder: 19,
      username: "cust09",
      items: [
        { id: 5, quantity: 1, unitPrice: 85, amountPrice: 85 },
        { id: 2, quantity: 1, unitPrice: 68, amountPrice: 68 },
      ],
      totalPrice: 153,
      date: "2025-10-23T00:00:00.000Z",
      userDeliveryPhone: "0901000009",
      userDeliveryAdress: "Da Lat, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 20,
      username: "cust10",
      items: [{ id: 3, quantity: 2, unitPrice: 72, amountPrice: 144 }],
      totalPrice: 144,
      date: "2025-10-22T00:00:00.000Z",
      userDeliveryPhone: "0901000010",
      userDeliveryAdress: "Bien Hoa, Vietnam",
      status: "cancelled",
    },
    // 20
    {
      idOrder: 21,
      username: "cust01",
      items: [{ id: 4, quantity: 1, unitPrice: 65, amountPrice: 65 }],
      totalPrice: 65,
      date: "2025-10-21T00:00:00.000Z",
      userDeliveryPhone: "0901000001",
      userDeliveryAdress: "Hanoi, Vietnam",
      status: "new",
    },
    {
      idOrder: 22,
      username: "cust02",
      items: [{ id: 6, quantity: 2, unitPrice: 78, amountPrice: 156 }],
      totalPrice: 156,
      date: "2025-10-20T00:00:00.000Z",
      userDeliveryPhone: "0901000002",
      userDeliveryAdress: "Ho Chi Minh City, Vietnam",
      status: "processing",
    },
    {
      idOrder: 23,
      username: "cust03",
      items: [{ id: 7, quantity: 1, unitPrice: 82, amountPrice: 82 }],
      totalPrice: 82,
      date: "2025-10-19T00:00:00.000Z",
      userDeliveryPhone: "0901000003",
      userDeliveryAdress: "Da Nang, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 24,
      username: "cust04",
      items: [{ id: 8, quantity: 2, unitPrice: 76, amountPrice: 152 }],
      totalPrice: 152,
      date: "2025-10-18T00:00:00.000Z",
      userDeliveryPhone: "0901000004",
      userDeliveryAdress: "Hai Phong, Vietnam",
      status: "cancelled",
    },
    {
      idOrder: 25,
      username: "cust05",
      items: [{ id: 9, quantity: 1, unitPrice: 88, amountPrice: 88 }],
      totalPrice: 88,
      date: "2025-10-17T00:00:00.000Z",
      userDeliveryPhone: "0901000005",
      userDeliveryAdress: "Can Tho, Vietnam",
      status: "new",
    },
    {
      idOrder: 26,
      username: "cust06",
      items: [{ id: 10, quantity: 1, unitPrice: 95, amountPrice: 95 }],
      totalPrice: 95,
      date: "2025-10-16T00:00:00.000Z",
      userDeliveryPhone: "0901000006",
      userDeliveryAdress: "Nha Trang, Vietnam",
      status: "processing",
    },
    {
      idOrder: 27,
      username: "cust07",
      items: [{ id: 11, quantity: 1, unitPrice: 85, amountPrice: 85 }],
      totalPrice: 85,
      date: "2025-10-15T00:00:00.000Z",
      userDeliveryPhone: "0901000007",
      userDeliveryAdress: "Hue, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 28,
      username: "cust08",
      items: [{ id: 12, quantity: 3, unitPrice: 62, amountPrice: 186 }],
      totalPrice: 186,
      date: "2025-10-14T00:00:00.000Z",
      userDeliveryPhone: "0901000008",
      userDeliveryAdress: "Vung Tau, Vietnam",
      status: "cancelled",
    },
    {
      idOrder: 29,
      username: "cust09",
      items: [{ id: 13, quantity: 1, unitPrice: 64, amountPrice: 64 }],
      totalPrice: 64,
      date: "2025-10-13T00:00:00.000Z",
      userDeliveryPhone: "0901000009",
      userDeliveryAdress: "Da Lat, Vietnam",
      status: "new",
    },
    {
      idOrder: 30,
      username: "cust10",
      items: [{ id: 14, quantity: 2, unitPrice: 70, amountPrice: 140 }],
      totalPrice: 140,
      date: "2025-10-12T00:00:00.000Z",
      userDeliveryPhone: "0901000010",
      userDeliveryAdress: "Bien Hoa, Vietnam",
      status: "processing",
    },
    // 30
    {
      idOrder: 31,
      username: "cust01",
      items: [{ id: 15, quantity: 1, unitPrice: 73, amountPrice: 73 }],
      totalPrice: 73,
      date: "2025-10-11T00:00:00.000Z",
      userDeliveryPhone: "0901000001",
      userDeliveryAdress: "Hanoi, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 32,
      username: "cust02",
      items: [{ id: 16, quantity: 2, unitPrice: 80, amountPrice: 160 }],
      totalPrice: 160,
      date: "2025-10-10T00:00:00.000Z",
      userDeliveryPhone: "0901000002",
      userDeliveryAdress: "Ho Chi Minh City, Vietnam",
      status: "cancelled",
    },
    {
      idOrder: 33,
      username: "cust03",
      items: [{ id: 17, quantity: 1, unitPrice: 86, amountPrice: 86 }],
      totalPrice: 86,
      date: "2025-10-09T00:00:00.000Z",
      userDeliveryPhone: "0901000003",
      userDeliveryAdress: "Da Nang, Vietnam",
      status: "new",
    },
    {
      idOrder: 34,
      username: "cust04",
      items: [
        { id: 18, quantity: 1, unitPrice: 55, amountPrice: 55 },
        { id: 19, quantity: 1, unitPrice: 58, amountPrice: 58 },
      ],
      totalPrice: 113,
      date: "2025-10-08T00:00:00.000Z",
      userDeliveryPhone: "0901000004",
      userDeliveryAdress: "Hai Phong, Vietnam",
      status: "processing",
    },
    {
      idOrder: 35,
      username: "cust05",
      items: [{ id: 1, quantity: 2, unitPrice: 75, amountPrice: 150 }],
      totalPrice: 150,
      date: "2025-10-07T00:00:00.000Z",
      userDeliveryPhone: "0901000005",
      userDeliveryAdress: "Can Tho, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 36,
      username: "cust06",
      items: [{ id: 2, quantity: 1, unitPrice: 68, amountPrice: 68 }],
      totalPrice: 68,
      date: "2025-10-06T00:00:00.000Z",
      userDeliveryPhone: "0901000006",
      userDeliveryAdress: "Nha Trang, Vietnam",
      status: "cancelled",
    },
    {
      idOrder: 37,
      username: "cust07",
      items: [{ id: 3, quantity: 1, unitPrice: 72, amountPrice: 72 }],
      totalPrice: 72,
      date: "2025-10-05T00:00:00.000Z",
      userDeliveryPhone: "0901000007",
      userDeliveryAdress: "Hue, Vietnam",
      status: "new",
    },
    {
      idOrder: 38,
      username: "cust08",
      items: [{ id: 4, quantity: 1, unitPrice: 65, amountPrice: 65 }],
      totalPrice: 65,
      date: "2025-10-04T00:00:00.000Z",
      userDeliveryPhone: "0901000008",
      userDeliveryAdress: "Vung Tau, Vietnam",
      status: "processing",
    },
    {
      idOrder: 39,
      username: "cust09",
      items: [{ id: 5, quantity: 1, unitPrice: 85, amountPrice: 85 }],
      totalPrice: 85,
      date: "2025-10-03T00:00:00.000Z",
      userDeliveryPhone: "0901000009",
      userDeliveryAdress: "Da Lat, Vietnam",
      status: "delivered",
    },
    {
      idOrder: 40,
      username: "cust10",
      items: [{ id: 6, quantity: 1, unitPrice: 78, amountPrice: 78 }],
      totalPrice: 78,
      date: "2025-10-02T00:00:00.000Z",
      userDeliveryPhone: "0901000010",
      userDeliveryAdress: "Bien Hoa, Vietnam",
      status: "cancelled",
    },
  ],
  importOrders: [
    {
      id: 1,
      idImportOrders: 1,
      quantity: 10,
      unitImportPrice: 45,
      amountPrice: 450,
      date: "2025-09-30T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 2,
      idImportOrders: 2,
      quantity: 8,
      unitImportPrice: 41,
      amountPrice: 328,
      date: "2025-09-29T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 3,
      idImportOrders: 3,
      quantity: 12,
      unitImportPrice: 43,
      amountPrice: 516,
      date: "2025-09-28T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 4,
      idImportOrders: 4,
      quantity: 6,
      unitImportPrice: 39,
      amountPrice: 234,
      date: "2025-09-27T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 5,
      idImportOrders: 5,
      quantity: 15,
      unitImportPrice: 51,
      amountPrice: 765,
      date: "2025-09-26T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 6,
      idImportOrders: 6,
      quantity: 7,
      unitImportPrice: 47,
      amountPrice: 329,
      date: "2025-09-25T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 7,
      idImportOrders: 7,
      quantity: 9,
      unitImportPrice: 49,
      amountPrice: 441,
      date: "2025-09-24T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 8,
      idImportOrders: 8,
      quantity: 10,
      unitImportPrice: 46,
      amountPrice: 460,
      date: "2025-09-23T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 9,
      idImportOrders: 9,
      quantity: 5,
      unitImportPrice: 53,
      amountPrice: 265,
      date: "2025-09-22T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 10,
      idImportOrders: 10,
      quantity: 6,
      unitImportPrice: 57,
      amountPrice: 342,
      date: "2025-09-21T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 11,
      idImportOrders: 11,
      quantity: 8,
      unitImportPrice: 51,
      amountPrice: 408,
      date: "2025-09-20T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 12,
      idImportOrders: 12,
      quantity: 10,
      unitImportPrice: 37,
      amountPrice: 370,
      date: "2025-09-19T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 13,
      idImportOrders: 13,
      quantity: 9,
      unitImportPrice: 38,
      amountPrice: 342,
      date: "2025-09-18T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 14,
      idImportOrders: 14,
      quantity: 7,
      unitImportPrice: 42,
      amountPrice: 294,
      date: "2025-09-17T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 15,
      idImportOrders: 15,
      quantity: 6,
      unitImportPrice: 44,
      amountPrice: 264,
      date: "2025-09-16T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 16,
      idImportOrders: 16,
      quantity: 11,
      unitImportPrice: 48,
      amountPrice: 528,
      date: "2025-09-15T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 17,
      idImportOrders: 17,
      quantity: 5,
      unitImportPrice: 52,
      amountPrice: 260,
      date: "2025-09-14T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 18,
      idImportOrders: 18,
      quantity: 12,
      unitImportPrice: 33,
      amountPrice: 396,
      date: "2025-09-13T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 19,
      idImportOrders: 19,
      quantity: 8,
      unitImportPrice: 35,
      amountPrice: 280,
      date: "2025-09-12T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 1,
      idImportOrders: 20,
      quantity: 6,
      unitImportPrice: 45,
      amountPrice: 270,
      date: "2025-09-11T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 2,
      idImportOrders: 21,
      quantity: 7,
      unitImportPrice: 41,
      amountPrice: 287,
      date: "2025-09-10T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 3,
      idImportOrders: 22,
      quantity: 5,
      unitImportPrice: 43,
      amountPrice: 215,
      date: "2025-09-09T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 4,
      idImportOrders: 23,
      quantity: 9,
      unitImportPrice: 39,
      amountPrice: 351,
      date: "2025-09-08T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 5,
      idImportOrders: 24,
      quantity: 10,
      unitImportPrice: 51,
      amountPrice: 510,
      date: "2025-09-07T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 6,
      idImportOrders: 25,
      quantity: 8,
      unitImportPrice: 47,
      amountPrice: 376,
      date: "2025-09-06T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 7,
      idImportOrders: 26,
      quantity: 6,
      unitImportPrice: 49,
      amountPrice: 294,
      date: "2025-09-05T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 8,
      idImportOrders: 27,
      quantity: 14,
      unitImportPrice: 46,
      amountPrice: 644,
      date: "2025-09-04T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 9,
      idImportOrders: 28,
      quantity: 7,
      unitImportPrice: 53,
      amountPrice: 371,
      date: "2025-09-03T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 10,
      idImportOrders: 29,
      quantity: 5,
      unitImportPrice: 57,
      amountPrice: 285,
      date: "2025-09-02T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 11,
      idImportOrders: 30,
      quantity: 9,
      unitImportPrice: 51,
      amountPrice: 459,
      date: "2025-09-01T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 12,
      idImportOrders: 31,
      quantity: 6,
      unitImportPrice: 37,
      amountPrice: 222,
      date: "2025-08-31T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 13,
      idImportOrders: 32,
      quantity: 8,
      unitImportPrice: 38,
      amountPrice: 304,
      date: "2025-08-30T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 14,
      idImportOrders: 33,
      quantity: 10,
      unitImportPrice: 42,
      amountPrice: 420,
      date: "2025-08-14T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 15,
      idImportOrders: 34,
      quantity: 7,
      unitImportPrice: 44,
      amountPrice: 308,
      date: "2025-08-13T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 16,
      idImportOrders: 35,
      quantity: 5,
      unitImportPrice: 48,
      amountPrice: 240,
      date: "2025-08-12T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 17,
      idImportOrders: 36,
      quantity: 6,
      unitImportPrice: 52,
      amountPrice: 312,
      date: "2025-08-11T00:00:00.000Z",
      status: "delivered",
    },
    {
      id: 18,
      idImportOrders: 37,
      quantity: 9,
      unitImportPrice: 33,
      amountPrice: 297,
      date: "2025-08-10T00:00:00.000Z",
      status: "processing",
    },
    {
      id: 19,
      idImportOrders: 38,
      quantity: 11,
      unitImportPrice: 35,
      amountPrice: 385,
      date: "2025-08-09T00:00:00.000Z",
      status: "delivered",
    },
  ],
};
